repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ --fix=no ]
      - id: name-tests-test
        args: [ --pytest-test-first ]
        files: ^tests/integration/.*\.py|tests/unit/.*\.py$
      - id: sort-simple-yaml
        files: ^(\.github/workflows/.*\.ya?ml|\.readthedocs.ya?ml)$
      - id: trailing-whitespace

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        files: ^(.*\.toml)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ --exit-non-zero-on-fix, --fix ]
        files: ^(docstrfmt/.*.py)$

  - repo: https://github.com/psf/black
    hooks:
      - id: black
    rev: 25.1.0

  - repo: https://github.com/LilSpazJoekp/docstrfmt
    hooks:
      - id: docstrfmt
    rev: v1.10.0
