jobs:
  pre-commit_autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Update hooks
        run: pre-commit autoupdate
      - name: Run hooks
        run: pre-commit run --all-files
        continue-on-error: true
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: Update pre-commit hooks
          body: Update versions of pre-commit hooks to the latest version.
name: Update pre-commit hooks
on:
  schedule:
    - cron: 0 15 * * 1
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
